---
name: Lorenzo
surname: Fabbri
position: "PhD Student"
address: "Barcelona Institute for Global Health"
#phone:
www: lorenzofabbri.github.io/
email: "lorenzo.fabbri@isglobal.org"
linkedin: lorenzo-fabbri-418721180
github: lorenzoFabbri
twitter: lorenzoF92SM
orcid: 0000-0003-3031-322X
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 0c9c2e
output:
  vitae::awesomecv
linkcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)

library(vitae)
library(tibble)
library(dplyr)
library(plyr)
library(scholar)
library(stringr)
library(glue)
library(lubridate)
library(zoo)
library(rorcid)
library(kableExtra)
```

# Research Interests

 * Exposomics and Epidemiology
 * Multi-Omics Data Integration
 * Causal Inference and Bayesian Methods for High-Dimensional Data
 
# Education

```{r}
edu <- rorcid::orcid_educations("0000-0003-3031-322X")$`0000-0003-3031-322X`$`affiliation-group`$summaries %>%
  plyr::rbind.fill(.)
edu$details <- list(
  c("Projects: HELIX, ATHLETE, OBERON
  \\begin{itemize}
      \\item Supervisors: Prof. Martine Vrijheid (ISGlobal), Dr. Lea Maitre (ISGlobal)
    \\end{itemize}"), 
  c("Master thesis (FBK, Trento): \\href{https://gitlab.com/lorenzo.fabbri92sm/master-thesis-fbk}{Machine Learning for Predictive Drug-Induced Hepatotoxicity}
  \\begin{itemize}
      \\item Supervisors: Dr. Cesare Furlanello (FBK), Dr. Marco Chierici (FBK), Prof. Enrico Domenici (UNITN)
    \\end{itemize}", 
    "Internship (HITS, Heidelberg): \\href{https://gitlab.com/lorenzo.fabbri92sm/master-thesis-hits}{Machine and Deep Learning for Predictive Unbinding Kinetics of Kinases}
    \\begin{itemize}
      \\item Supervisors: Prof. Rebecca Wade (HITS), Dr. Daria Kokh (HITS), Prof. Raffaello Potestio (UNITN)
    \\end{itemize}", 
    "Final mark: 110/110 With Honors"), 
  c("Project: Investigation by Computational Techniques of Channelopaties related to Sodium Channels
  \\begin{itemize}
      \\item Supervisors: Prof. Vittorio Limongelli (USI), Prof. Daniele Di Marino (USI)
    \\end{itemize}"), 
  c("Bachelor thesis (RWTH, Aachen): Whole-body PBPK Modeling of Valproic Acid
  \\begin{itemize}
      \\item Supervisors: Prof. Elena Maestri (UNIPR), Prof. Lars M. Blank (RWTH), Dr. Henrik Cordes (RWTH)
    \\end{itemize}", 
    "Final mark: 103/110")
)

edu %>%
  vitae::detailed_entries(
    what = `education-summary.role-title`, 
    when = glue::glue("{`education-summary.start-date.year.value`} - {`education-summary.end-date.year.value`}", 
                      .na = ""), 
    with = `education-summary.organization.name`, 
    where = `education-summary.organization.address.city`, 
    why = details, 
    .protect = FALSE
  )
```

# Continuing Education

```{r}
tibble::tribble(
  ~ Course, ~ Institution, ~ Where, ~ Dates, 
  "Advanced Course in Alternatives to Animal Experimentation", 
    "University of Genova", "Genoa, Italy", "November 1, 2015", 
  "MARVEL School on Variationally Enhanced Sampling", 
    "University of Lugano", "Lugano, Switzerland", "February 1, 2017", 
  "Effective High Performance Computing Summer School", 
    "CSCS and University of Lugano", "Lugano, Switzerland", "July 1, 2017", 
  "Image Analysis and Modeling of Complex Biological Dynamics", 
    "University of Wurzburg", "Wurzburg, Germany", "September 1, 2017", 
  "Mendelian Randomisation", "Imperial College London", "Online", "May 1, 2020", 
  "Metabolomics Data Processing and Data Analysis", 
    "University of Birmingham", "Online", "February 1, 2021", 
  "Alpine Exposome Summer School", "Inserm and ATHLETE", "Online", "June 1, 2021", 
  "Advanced Statistics: Statistical Modelling", 
    "Swiss Institute of Bioinformatics", "Online", "August 1, 2021", 
  "ELIXIR Omics Integration and Systems Biology", 
    "National Bioinformatics Infrastructure Sweden", "Online", "September 1, 2021"
) %>%
  dplyr::mutate(., Dates = zoo::as.yearmon(lubridate::mdy(Dates))) %>%
  dplyr::arrange(desc(Dates)) %>%
  vitae::brief_entries(
    glue::glue("\\textbf{<Course>} (<Institution>, <Where>)", 
               .open = "<", .close = ">", .na = ""), 
    Dates, 
    .protect = FALSE
  )
```

# Working Experience

```{r}
emp <- rorcid::orcid_employments("0000-0003-3031-322X")$`0000-0003-3031-322X`$`affiliation-group`$summaries %>%
  plyr::rbind.fill(.)
emp %>%
  vitae::detailed_entries(
    what = `employment-summary.role-title`, 
    when = glue::glue("{`employment-summary.start-date.year.value`} - {`employment-summary.end-date`}", 
                      .na = ""), 
    with = `employment-summary.organization.name`, 
    where = `employment-summary.organization.address.city`
  )
```

# Skills

```{r}
tibble::tribble(
  ~ Languages, ~ `Programming Languages`, ~ `Markup Languages`, ~ `Software Development`, 
  "Italian (native), English (C1, IELTS 7.0), Spanish (basic)", 
  "R, Python, MATLAB, SAS, C", 
  "\\LaTeX, RMarkdown", 
  "GIT, SLURM, High-Performance Scientific Computing"
) %>%
  knitr::kable(booktabs = T, align = 'c', escape = F, format = "latex") %>%
  kableExtra::kable_styling(full_width = F, font_size = 9, 
                            latex_options = "hold_position") %>%
  kableExtra::row_spec(0, bold = T) %>%
  kableExtra::row_spec(1, bold = F) %>%
  kableExtra::column_spec(column = 1:4, width = '4.cm')
```

# Honors and Awards

```{r}
fu <- rorcid::orcid_fundings("0000-0003-3031-322X")$`0000-0003-3031-322X`$group$`funding-summary` %>%
  plyr::rbind.fill(.) %>%
  dplyr::select(title.title.value, `start-date.year.value`, organization.name)
fu.manual <- tibble::tribble(
  ~ title.title.value, ~ `start-date.year.value`, ~ organization.name, 
  "Erasmus+ Traineeship Programme Scholarship", 2019, "Università degli Studi di Trento", 
  "Student Research Assistant Fellowship", 2017, "Università della Svizzera italiana", 
  "Faculty of Informatics Scholarship", 2016, "Università della Svizzera italiana", 
  "Erasmus Traineeship Programme Scholarship", 2015, "Università degli Studi di Parma"
)
fu %>%
  plyr::rbind.fill(fu.manual) %>%
  dplyr::arrange(desc(`start-date.year.value`)) %>%
  vitae::brief_entries(
    what = glue::glue("\\textbf{<title.title.value>} (<organization.name>)", 
                      .open = "<", .close = ">", .na = ""), 
    when = `start-date.year.value`, 
    .protect = FALSE
  )
```

# Publications

```{r publications}
scholar::get_publications("QbPv1H0AAAAJ") %>%
  dplyr::mutate(author = author %>% as.character() %>% stringr::str_trim(), 
                journal = journal, 
                first_author = dplyr::case_when(stringr::str_starts(author, "L Fabbri") ~ TRUE, 
                                                TRUE ~ FALSE)) %>%
  dplyr::arrange(desc(year)) %>%
  vitae::detailed_entries(
    what = title, 
    when = as.character(year), 
    with = author, 
    where = journal
  )
```

# Conference Presentations

```{r}
conf <- rorcid::orcid_works("0000-0003-3031-322X")$`0000-0003-3031-322X`$works %>%
  plyr::rbind.fill(.)
conf[conf$`put-code` == "105548271", ]$title.title.value <- "Efficient and Portable MPI Support for Approximate Bayesian Computation"
conf[conf$`put-code` == "105548271", ]$`publication-date.year.value` <- 2017
conf[conf$`put-code` == "105548590", ]$`publication-date.year.value` <- 2022

conf %>%
  dplyr::filter(type == "conference-poster") %>%
  dplyr::arrange(desc(`publication-date.year.value`)) %>%
  vitae::detailed_entries(
    when = `publication-date.year.value`, 
    what = glue::glue("\\href{<url.value>}{<title.title.value>}", 
                     .open = "<", .close = ">", .na = ""), 
    .protect = FALSE
  )
```
